/* Generated by tools/genfont.py - do not edit by hand. */
#ifndef FONT_ZH_H
#define FONT_ZH_H

#include <stdint.h>

#define FONT_ZH_SIZE   24
#define FONT_ZH_STRIDE 3
#define FONT_ZH_BYTES  72
#define FONT_ZH_COUNT  74

/* Codepoints, ascending. Parallel to font_zh_bitmap. */
extern const uint16_t font_zh_cp[FONT_ZH_COUNT];
extern const uint8_t  font_zh_bitmap[FONT_ZH_COUNT][FONT_ZH_BYTES];

/* Returns the glyph bitmap for a codepoint, or NULL if absent. */
const uint8_t *font_zh_glyph(uint16_t cp);

#endif /* FONT_ZH_H */
