#!/usr/bin/env python3
"""Generate a bitmap font table for the Traditional Chinese glyphs the game
needs, plus ASCII digits and a few symbols.

Renders with Microsoft JhengHei and emits a C source + header holding a sorted
glyph table, so the firmware can binary-search a codepoint at draw time.
"""
import sys
from PIL import Image, ImageDraw, ImageFont

# Every character the UI can show. Keep this in sync with the strings in ui.c.
GLYPHS = (
    "0123456789"
    ":+-/%"
    "ABXY"          # SNES-style face-button labels
    "分數等級行消暫停繼續遊戲結束再玩一次下個保留最高新紀錄"
    "左右轉落快速旋開始按住放乘重來返回關閉音效"
    "俄羅斯方塊到鍵"
)

SIZE = 24          # cell size in pixels (square)
FONT_PATH = r"C:\Windows\Fonts\msjhbd.ttc"   # bold reads better on an LCD


def render(ch, font, size):
    """Render one glyph into a size x size 1-bit bitmap, centred."""
    img = Image.new("L", (size, size), 0)
    draw = ImageDraw.Draw(img)

    # Measure and centre. Chinese glyphs are square; latin ones are narrow.
    try:
        bbox = draw.textbbox((0, 0), ch, font=font)
    except Exception:
        bbox = (0, 0, size, size)
    w = bbox[2] - bbox[0]
    h = bbox[3] - bbox[1]
    x = (size - w) // 2 - bbox[0]
    y = (size - h) // 2 - bbox[1]
    draw.text((x, y), ch, font=font, fill=255)

    # Threshold to 1bpp, packed rows, MSB first.
    rows = []
    px = img.load()
    for r in range(size):
        bits = bytearray((size + 7) // 8)
        for c in range(size):
            if px[c, r] >= 128:
                bits[c >> 3] |= 0x80 >> (c & 7)
        rows.append(bytes(bits))
    return b"".join(rows)


def main():
    # Deduplicate but keep it deterministic, then sort by codepoint so the
    # firmware can binary-search.
    chars = sorted(set(GLYPHS))

    # Some fonts need a size hint smaller than the cell to avoid clipping.
    font = ImageFont.truetype(FONT_PATH, SIZE - 4, index=0)

    stride = (SIZE + 7) // 8
    bytes_per_glyph = stride * SIZE

    blobs = []
    for ch in chars:
        data = render(ch, font, SIZE)
        assert len(data) == bytes_per_glyph, (ch, len(data))
        blobs.append((ch, data))

    with open("core/font_zh.h", "w", encoding="utf-8") as f:
        f.write(f"""/* Generated by tools/genfont.py - do not edit by hand. */
#ifndef FONT_ZH_H
#define FONT_ZH_H

#include <stdint.h>

#define FONT_ZH_SIZE   {SIZE}
#define FONT_ZH_STRIDE {stride}
#define FONT_ZH_BYTES  {bytes_per_glyph}
#define FONT_ZH_COUNT  {len(blobs)}

/* Codepoints, ascending. Parallel to font_zh_bitmap. */
extern const uint16_t font_zh_cp[FONT_ZH_COUNT];
extern const uint8_t  font_zh_bitmap[FONT_ZH_COUNT][FONT_ZH_BYTES];

/* Returns the glyph bitmap for a codepoint, or NULL if absent. */
const uint8_t *font_zh_glyph(uint16_t cp);

#endif /* FONT_ZH_H */
""")

    with open("core/font_zh.c", "w", encoding="utf-8") as f:
        f.write("/* Generated by tools/genfont.py - do not edit by hand. */\n")
        f.write('#include "font_zh.h"\n\n')

        f.write(f"const uint16_t font_zh_cp[FONT_ZH_COUNT] = {{\n")
        for i in range(0, len(blobs), 8):
            row = blobs[i:i + 8]
            f.write("    " + " ".join(f"0x{ord(c):04X}," for c, _ in row))
            f.write("   /* " + "".join(c for c, _ in row) + " */\n")
        f.write("};\n\n")

        f.write("const uint8_t font_zh_bitmap[FONT_ZH_COUNT][FONT_ZH_BYTES] = {\n")
        for ch, data in blobs:
            f.write(f"    {{ /* U+{ord(ch):04X} {ch} */\n")
            for r in range(SIZE):
                row = data[r * stride:(r + 1) * stride]
                f.write("        " + " ".join(f"0x{b:02X}," for b in row) + "\n")
            f.write("    },\n")
        f.write("};\n\n")

        f.write("""const uint8_t *font_zh_glyph(uint16_t cp)
{
    /* Binary search over the ascending codepoint table. */
    int lo = 0, hi = FONT_ZH_COUNT - 1;
    while (lo <= hi) {
        int mid = (lo + hi) / 2;
        if (font_zh_cp[mid] == cp) {
            return font_zh_bitmap[mid];
        }
        if (font_zh_cp[mid] < cp) {
            lo = mid + 1;
        } else {
            hi = mid - 1;
        }
    }
    return 0;
}
""")

    total = len(blobs) * bytes_per_glyph
    print(f"glyphs: {len(blobs)}")
    print(f"cell:   {SIZE}x{SIZE}, {bytes_per_glyph} bytes each")
    print(f"table:  {total} bytes ({total/1024:.1f} KB)")

    # ASCII preview so we can eyeball a few glyphs without a board.
    for probe in "分數遊戲":
        data = dict(blobs).get(probe)
        if not data:
            continue
        print(f"\n--- {probe} ---")
        for r in range(SIZE):
            row = data[r * stride:(r + 1) * stride]
            line = ""
            for c in range(SIZE):
                line += "#" if (row[c >> 3] >> (7 - (c & 7))) & 1 else "."
            print(line)


if __name__ == "__main__":
    sys.exit(main())
